import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { supabase } from './lib/supabase'

type Status = 'draft' | 'live' | 'closed'
type PollType = 'choice' | 'qa'
type Poll = { id: string; title: string; question: string; type: PollType; status: Status; created_at: string }
type Option = { id: string; poll_id: string; option_text: string; display_order: number }
type Vote = { id: string; poll_id: string; option_id: string; created_at: string }
type Question = { id: string; poll_id: string; question_text: string; upvotes: number; created_at: string }

const colors = ['#635bff','#8b5cf6','#06b6d4','#f59e0b','#ec4899','#22c55e']
const joinUrl = (id: string) => `${window.location.origin}/vote/${id}`

function StatusBadge({ status }: { status: Status }) { return <span className={`badge ${status}`}>{status}</span> }
function Brand({ dark = false }: { dark?: boolean }) { return <Link className={`brand ${dark ? 'darkbrand' : ''}`} to="/"><i>●</i> PulseLive</Link> }
function usePollData(id?: string) {
  const [poll, setPoll] = useState<Poll | null>(null); const [options, setOptions] = useState<Option[]>([]); const [votes, setVotes] = useState<Vote[]>([]); const [questions, setQuestions] = useState<Question[]>([]); const [loading, setLoading] = useState(true)
  const refresh = async () => { if (!id) return; setLoading(true); const [p,o,v,q] = await Promise.all([supabase.from('polls').select('*').eq('id',id).single(),supabase.from('options').select('*').eq('poll_id',id).order('display_order'),supabase.from('votes').select('*').eq('poll_id',id),supabase.from('questions').select('*').eq('poll_id',id).order('upvotes',{ascending:false})]); setPoll(p.data); setOptions(o.data || []); setVotes(v.data || []); setQuestions(q.data || []); setLoading(false) }
  useEffect(() => { refresh(); if (!id) return; const channel = supabase.channel(`poll-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'polls',filter:`id=eq.${id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'options',filter:`poll_id=eq.${id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'votes',filter:`poll_id=eq.${id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'questions',filter:`poll_id=eq.${id}`},refresh).subscribe(); return () => { supabase.removeChannel(channel) } }, [id])
  return { poll, options, votes, questions, loading, refresh }
}

function Results({ poll, options, votes, questions, large = false }: { poll: Poll; options: Option[]; votes: Vote[]; questions: Question[]; large?: boolean }) {
  if (poll.type === 'qa') return <div className={`questions ${large ? 'large-results' : ''}`}>{questions.length ? questions.map((q,i) => <div className="question-item" key={q.id}><span className="rank">{i + 1}</span><p>{q.question_text}</p><b>▲ {q.upvotes}</b></div>) : <div className="results-empty">Questions from your audience will appear here.</div>}</div>
  const max = Math.max(...options.map(o => votes.filter(v => v.option_id === o.id).length), 1)
  return <div className={`bars ${large ? 'large-results' : ''}`}>{options.map((o,i) => { const n=votes.filter(v=>v.option_id===o.id).length; const percent=Math.round(n / Math.max(votes.length,1)*100); return <div className="bar-row" key={o.id}><div className="bar-label"><span>{o.option_text}</span><b>{n} <small>({percent}%)</small></b></div><div className="track"><div className="fill" style={{ width: `${n/max*100}%`, background: colors[i] }} /></div></div>})}</div>
}

function Dashboard() { const [polls,setPolls]=useState<Poll[]>([]); const [counts,setCounts]=useState<Record<string,number>>({}); const [loading,setLoading]=useState(true)
  useEffect(()=>{ const load=async()=>{setLoading(true); const {data}=await supabase.from('polls').select('*').order('created_at',{ascending:false}); const list=data||[]; setPolls(list); const response=await Promise.all(list.map(async p=> { const table=p.type==='choice'?'votes':'questions'; const {count}=await supabase.from(table).select('*',{count:'exact',head:true}).eq('poll_id',p.id); return [p.id,count||0] as const })); setCounts(Object.fromEntries(response)); setLoading(false)}; load(); const c=supabase.channel('dashboard').on('postgres_changes',{event:'*',schema:'public',table:'polls'},load).on('postgres_changes',{event:'*',schema:'public',table:'votes'},load).on('postgres_changes',{event:'*',schema:'public',table:'questions'},load).subscribe(); return()=>{supabase.removeChannel(c)}},[])
  return <main className="shell"><nav><Brand/><Link className="button" to="/create">+ Create new poll</Link></nav><header className="page-heading"><div><p className="eyebrow">PRESENTER DASHBOARD</p><h1>Make the room part of it.</h1><p>Launch interactive polls and hear from every voice.</p></div></header>{loading?<div className="loading">Loading your polls…</div>:polls.length?<section className="poll-grid">{polls.map(p=><Link to={`/poll/${p.id}`} className="poll-card" key={p.id}><div><StatusBadge status={p.status}/><span className="type">{p.type==='choice'?'Multiple choice':'Q&A'}</span></div><h2>{p.title}</h2><p>{p.question}</p><footer><b>{counts[p.id]||0}</b> responses <span>Manage →</span></footer></Link>)}</section>:<section className="empty"><div className="empty-icon">◌</div><h2>Your stage is ready.</h2><p>Create your first poll and invite the room to join in.</p><Link className="button" to="/create">Create your first poll</Link></section>}</main> }

function CreatePoll() { const nav=useNavigate(); const [title,setTitle]=useState(''); const [question,setQuestion]=useState(''); const [type,setType]=useState<PollType>('choice'); const [options,setOptions]=useState(['','']); const [busy,setBusy]=useState(false); const submit=async(e:FormEvent)=>{e.preventDefault(); if(!title.trim()||!question.trim()||(type==='choice'&&options.some(x=>!x.trim())))return;setBusy(true); const {data,error}=await supabase.from('polls').insert({title,question,type,status:'draft'}).select().single(); if(error||!data){alert(error?.message||'Could not create poll');setBusy(false);return} if(type==='choice'){const {error:oe}=await supabase.from('options').insert(options.map((option_text,display_order)=>({poll_id:data.id,option_text,display_order})));if(oe){alert(oe.message);setBusy(false);return}}nav(`/poll/${data.id}`)}; return <main className="shell narrow"><nav><Brand/><Link className="text-link" to="/">← Dashboard</Link></nav><section className="form-card"><p className="eyebrow">NEW INTERACTION</p><h1>Create a poll</h1><form onSubmit={submit}><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Team all-hands" /></label><label>Question<textarea required value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would you like to ask?" /></label><label>Type<div className="type-select"><button type="button" className={type==='choice'?'selected':''} onClick={()=>setType('choice')}>☷ <span><b>Multiple choice</b><small>Let people choose an answer</small></span></button><button type="button" className={type==='qa'?'selected':''} onClick={()=>setType('qa')}>◌ <span><b>Q&A</b><small>Collect audience questions</small></span></button></div></label>{type==='choice'&&<fieldset><legend>Answer options</legend>{options.map((o,i)=><div className="option-input" key={i}><span>{i+1}</span><input required value={o} onChange={e=>setOptions(options.map((x,n)=>n===i?e.target.value:x))} placeholder={`Option ${i+1}`}/>{i>1&&<button type="button" onClick={()=>setOptions(options.filter((_,n)=>n!==i))}>×</button>}</div>)}{options.length<6&&<button type="button" className="add" onClick={()=>setOptions([...options,''])}>+ Add option</button>}</fieldset>}<button className="button submit" disabled={busy}>{busy?'Creating…':'Create draft poll →'}</button></form></section></main> }

function PollManagement() { const {id=''}=useParams(); const {poll,options,votes,questions,loading,refresh}=usePollData(id); const nav=useNavigate(); const [confirm,setConfirm]=useState(false); if(loading)return <div className="loading">Loading poll…</div>; if(!poll)return <Navigate to="/"/>; const update=async(status:Status)=>{await supabase.from('polls').update({status}).eq('id',id);refresh()}; const reset=async()=>{const table=poll.type==='choice'?'votes':'questions';await supabase.from(table).delete().eq('poll_id',id);setConfirm(false);refresh()}; const copy=()=>navigator.clipboard.writeText(joinUrl(id)); return <main className="shell"><nav><Brand/><Link className="text-link" to="/">← Dashboard</Link></nav><header className="manage-head"><div><p className="eyebrow">{poll.type==='choice'?'MULTIPLE CHOICE':'AUDIENCE Q&A'}</p><h1>{poll.title}</h1><p>{poll.question}</p></div><StatusBadge status={poll.status}/></header><div className="manage-grid"><aside className="join-card"><p className="eyebrow">JOIN THE POLL</p><div className="qr"><QRCodeSVG value={joinUrl(id)} size={180} /></div><p className="join-url">{joinUrl(id)}</p><button className="copy" onClick={copy}>Copy link</button><div className="controls"><p>Poll status</p><div><button className={poll.status==='live'?'live-control active':'live-control'} onClick={()=>update('live')}>● Open voting</button><button className="close-control" onClick={()=>update('closed')}>Close voting</button></div></div><Link className="button present-btn" to={`/poll/${id}/present`}>Present ↗</Link><button className="reset" onClick={()=>setConfirm(true)}>Reset results</button></aside><section className="results-card"><div className="results-top"><div><p className="eyebrow">LIVE RESULTS</p><h2>{poll.type==='choice'?`${votes.length} total votes`:`${questions.length} audience questions`}</h2></div><span className="live-dot">● LIVE</span></div><Results poll={poll} options={options} votes={votes} questions={questions}/></section></div>{confirm&&<div className="modal-back"><section className="modal"><h2>Reset results?</h2><p>This permanently clears all {poll.type==='choice'?'votes':'questions'} from this poll.</p><div><button className="copy" onClick={()=>setConfirm(false)}>Cancel</button><button className="danger" onClick={reset}>Yes, reset</button></div></section></div>}</main> }

function Present() { const {id=''}=useParams(); const {poll,options,votes,questions,loading}=usePollData(id); if(loading)return <div className="present loading">Loading presentation…</div>;if(!poll)return <Navigate to="/"/>;return <main className="present"><div className="present-brand">● PULSELIVE <span>LIVE</span></div><div className="present-copy"><p>{poll.title}</p><h1>{poll.question}</h1></div><Results poll={poll} options={options} votes={votes} questions={questions} large/><div className="present-qr"><QRCodeSVG value={joinUrl(id)} size={100}/><span>Scan to join</span></div></main> }

function Vote() { const {id=''}=useParams(); const {poll,options,votes,questions,loading,refresh}=usePollData(id); const [done,setDone]=useState(false); const [text,setText]=useState(''); const [submitting,setSubmitting]=useState(false); if(loading)return <main className="audience"><div className="loading">Loading…</div></main>;if(!poll)return <main className="audience"><Brand/><div className="not-open"><h1>Poll not found</h1></div></main>; const vote=async(option:string)=>{setSubmitting(true);const {error}=await supabase.from('votes').insert({poll_id:id,option_id:option});setSubmitting(false);if(error)alert(error.message);else{setDone(true);refresh()}}; const ask=async(e:FormEvent)=>{e.preventDefault();if(!text.trim())return;setSubmitting(true);const {error}=await supabase.from('questions').insert({poll_id:id,question_text:text.trim(),upvotes:0});setSubmitting(false);if(error)alert(error.message);else{setText('');refresh()}};const upvote=async(q:Question)=>{await supabase.from('questions').update({upvotes:q.upvotes+1}).eq('id',q.id);refresh()};return <main className="audience"><div className="audience-top"><Brand/><span>LIVE SESSION</span></div><section className="vote-content"><p className="eyebrow">{poll.title}</p><h1>{poll.question}</h1>{poll.status!=='live'?<div className="not-open"><div>⏱</div><h2>This poll isn't open for responses right now.</h2><p>Keep this page open — it may start soon.</p></div>:poll.type==='choice'?(done?<div className="thank"><div>✓</div><h2>Thanks for voting!</h2><p>Your response has been counted.</p><Results poll={poll} options={options} votes={votes} questions={questions}/></div>:<><div className="answers">{options.map(o=><button disabled={submitting} onClick={()=>vote(o.id)} key={o.id}>{o.option_text}<span>→</span></button>)}</div></>):<><form className="ask-form" onSubmit={ask}><textarea value={text} maxLength={500} onChange={e=>setText(e.target.value)} placeholder="Ask a question…"/><button className="button" disabled={submitting}>{submitting?'Sending…':'Submit question'}</button></form><section className="audience-questions"><h2>Questions from the room</h2>{questions.length?questions.map(q=><article key={q.id}><p>{q.question_text}</p><button onClick={()=>upvote(q)}>▲ {q.upvotes}</button></article>):<p className="muted">Be the first to ask a question.</p>}</section></>}</section></main> }

export default function App(){return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/create" element={<CreatePoll/>}/><Route path="/poll/:id" element={<PollManagement/>}/><Route path="/poll/:id/present" element={<Present/>}/><Route path="/vote/:id" element={<Vote/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
